### ISSUE TITLE
Move KAT Ammonium Carbonate and Painkillers from Magazines to Medical

### ISSUE THREAD

**Issue by Quailsnap** [johnb432/Improved-ACE-Arsenal-Category#1]
Making an issue to gauge feasibility -- what's preventing magazines from being moved to other categories? Is it an ACE Arsenal issue?

**Comment by johnb432** [comment]
> Making an issue to gauge feasibility -- what's preventing magazines from being moved to other categories? Is it an ACE Arsenal issue?

Yea, it's because of an ACE Arsenal limitation, see [here](https://github.com/acemod/ACE3/blob/eab93f739a17a2a40a10042f08bbf8909de228a5/addons/arsenal/functions/fnc_addRightPanelButton.sqf#L46).
